### ISSUE TITLE
Switch back to Python 3.x and revert Python 3.11 hack

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck-action#15]
For https://github.com/pkgcore/pkgcheck-action/issues/13, we switched to hardcoding 3.11 temporarily in 966e2235b9f86bf5f2af17cdffbb6d8bb59ddb16. We should undo that and properly support newer Pythons in the action.

**Comment by radhermit** [comment]
I think upstream tree-sitter python should move the distutils imports into the build_library() function and then all this would be solved as this action should be using the binary wheel with a pre-compiled tree-sitter bash library so no compiling at runtime is necessary if everything is set up correctly.

**Comment by radhermit** [comment]
Yet another option is making the action depend on another wheel providing pre-compiled tree-sitter-bash support which is a decent alternative if upstream tree-sitter is the maintainer for the wheel. There does appear to be third party wheels for various tree-sitter language support as well as one for all languages, but personally I'd avoid any third party wheels.
