### ISSUE TITLE
Warning annotations about set-output on each run

### ISSUE THREAD

**Issue by ferki** [pkgcore/pkgcheck-action#9]
The following warnings started to show up in the annotations on each run during

> pkgcheck
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Apparently it happens during the "Set up python" phase of "Run pkgcheck" step.

It seems like to be caused by depending on `github:actions/setup-python#v2` while it seems already fixed in `v4` of that project.

I'd be happy to send a PR to bump the version of the dependency, but I can't judge the full implications of that change, so I decided to open issue for now.

**Comment by ferki** [comment]
The issue seems to be fixed in actions/setup-python#517, which became part of their `v4` starting from v4.3.0. Also backported to `v2` on actions/setup-python#533.

If I understand correctly, the dependencies here are bundled, and described in `package.json`. Which this means it might be enough to simply regenerate files like `package-lock.json` and `dist/index.js` without any actual code changes.

I will try to open a draft pull request about that to gather further feedback.

**Comment by hololeap** [comment]
> On October 11, 2022, [we annouced plans](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) to deprecate the save-state and set-output workflow commands on May 31, 2023. We have since decided to postpone the removal given the amount of usage we are still seeing with these commands.
>
> Workflows using save-state or set-output in their workflows will continue to work as expected, however, a warning will appear under annotations indicating the planned deprecation. We recommend customers using these commands to upgrade their workflows to use environment files.

https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/

---

So, it doesn't look like the command will be removed any time soon, but finishing this PR will get rid of the warning.
